### ISSUE TITLE
OrderAcceptCustomerInput:: 郵便番号と都道府県

### ISSUE THREAD

**Issue by potomoppu** [in-the-box/pizza#101]
# 改善点
郵便番号のplaceholderにハイフンが入っている。
maxlength指定が７文字ではない。
郵便番号を入力すると住所が出る(aajxzip3)が未導入。
電話番号にマイナス値がはいる。
電話番号のmaxlength指定がない。
確認ボタンが反応しない。（データが送信できない）

**Comment by miniikit** [comment]
1.郵便番号のplaceholderにハイフンが入っている。
>>対処済み
2.maxlength指定が７文字ではない。
>>対処済み
3.郵便番号を入力すると住所が出る(aajxzip3)が未導入。
>>対処済み
4.電話番号にマイナス値がはいる。
>>仕様です
5.電話番号のmaxlength指定がない。
>>対処済み
確認ボタンが反応しない。（データが送信できない）
>>再現不可（対処済み）

>>クローズお願いします
