### ISSUE TITLE
OrderAcceptItem21Select#side :: サイドメニュー

### ISSUE THREAD

**Issue by potomoppu** [in-the-box/pizza#140]
商品選択中の画面で　画面横のカテゴリの　サイド　だけ　押しても飛ばない

Cartの中身が重複して表示される

**Comment by miniikit** [comment]
商品選択中の画面で　画面横のカテゴリの　サイド　だけ　押しても飛ばない >> 対処済み

Cartの中身が重複して表示される >> 対処済み

クローズお願いします
