### ISSUE TITLE
管理者クーポン編集:ID4のクーポン編集ページにアクセスできない

### ISSUE THREAD

**Issue by potomoppu** [in-the-box/pizza#141]
開催中クーポン一覧より、ID:4(クーポン名:期間限定 500円引きクーポン)を選び、編集ページに移動しようとすると、エラーが起きる。
エラー:ErrorException in CouponsController.php line 276:
Trying to get property of non-object

ちなみに、それ以外のクーポンは編集ページに移動できる。

**Comment by miniikit** [comment]
このエラーすでに直してる
