### ISSUE TITLE
OrderAcceptCustomerDetail:: お客様情報入力

### ISSUE THREAD

**Issue by potomoppu** [in-the-box/pizza#90]
#問題点

1. 名前(漢字)に英数字が入力できてしまう
2. 名前(カナ)でも同様のバグ
3. 郵便番号に数字を入れるとエラー表示される

**Comment by miniikit** [comment]
1.名前(漢字)に英数字が入力できてしまう
>>仕様です
名前(カナ)でも同様のバグ
>>仕様です
郵便番号に数字を入れるとエラー表示される
>>対処済み

>>クローズお願いします
